name: Gestao de Vagas Application

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Java
              uses: actions/setup-java
              with:
                distribution: temurim
                java-version: 17
